d8cards3_config_form.settings:
  type: config_object
  mapping:
    d8cards_text:
      type: string
      label: 'Example Text Field'
      translatable: true
    d8cards_radios:
      type: int
      label: 'Example Radios'
    d8cards_select:
      type: int
      lable: 'Example Select'
